[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["tokio", "http1"] }
tokio = { version = "1.41.0", features = ["full"] }
tracing = "0.1.40"
